# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# References:
# https://circleci.com/docs/2.0/language-python/
# https://circleci.com/docs/2.0/configuration-reference/

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            virtualenv -p python2.7 env
            source env/bin/activate
            pip install -r requirements.txt -r requirements-dev.txt
      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Lint
          command: flake8 pubsub_client/ tests/
      - run:
          name: Decode credentials
          command: |
            if [ -n "$ENCODED_CREDENTIALS" ]; then
              echo $ENCODED_CREDENTIALS | base64 --decode > credentials.json
            else
              echo "No credentials supplied. Tests will fail."
            fi
      - run:
          name: run tests
          command: |
            source env/bin/activate
            ./generate-compatibility-tests.sh
            export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/credentials.json
            python -m unittest discover | sed s/${GOOGLE_CLOUD_PROJECT}/PROJECT_ID/g
workflows:
  version: 2
  nightly:
     triggers:
       - schedule:
           cron: "0 0 * * *"
     jobs:
       - build
